version: 0.0
os: linux
files:
  - source: /geostore.war
    destination: /tmp
hooks:
  PreInstall:
    - location: install_apache_tomcat.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: install_database.sh
      timeout: 300
      runas: root
  DuringInstall:
    - location: run4MS.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: create_database.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: start-server.sh
      timeout: 180
      runas: root
