version: 0.0
os: linux
files:
  - source: /geostore.war
    destination: /tmp
hooks:
  BeforeInstall:
    - location: scripts/install_apache_tomcat.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_database.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/create_database.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 180
      runas: root