version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/tomcat/webapps
hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 180
      runas: ec2_user
   BeforeInstall:
    - location: install_database.sh
      timeout: 300
      runas: ec2_user
  Install:
    - location: run4MS.sh
      timeout: 300
      runas: ec2_user
  AfterInstall:
    - location: create_database.sh
      timeout: 300
      runas: ec2_user
  ApplicationStart:
    - location: start-server.sh
      timeout: 180
      runas: ec2_user
