version: 0.2

phases:
  install:
    commands:
      - echo Installing maven 
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo Building the seamfix-geostore project on 'date'
      - cd $CODEBUILD_SRC_DIR/src/
      - mvn clean install
  post_build:
    commands:
     - echo Buld completed for seamfix-geostore project on 'date'
     - mvn package
artifacts:
  files:
    - $CODEBUILD_SRC_DIR/**/*.war
    - $CODEBUILD_SRC_DIR/clean4MS.sh
    - $CODEBUILD_SRC_DIR/run4MS.sh
    - $CODEBUILD_SRC_DIR/appspec.yml
    - $CODEBUILD_SRC_DIR/scripts/*
    - $CODEBUILD_SRC_DIR/**/sql/*
  discard-paths: yes
