version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update -y
      - sudo apt-get install -y maven
  build:
    commands:
      - echo Building the seamfix-geostore project on 'date'
      - cd $CODEBUILD_SRC_DIR/src/
      - mvn clean install
  post_build:
    commands:
     - echo Buld completed for seamfix-geostore project on 'date'
     - mvn package
artifacts:
  files:
     - $CODEBUILD_SRC_DIR/src/web/app/target/*
     - $CODEBUILD_SRC_DIR/src/web/app/pom.xml
     - run4MS.sh
     - appspec.yml
     - scripts/*
  discard-paths: yes
