version: 0.2

phases:
  install:
    commands:
      - echo Installing maven 
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo Building the seamfix-geostore project on 'date'
      - mvn clean install
  post_build:
    commands:
     - echo Buld completed for seamfix-geostore project on 'date'
     - mvn package
artifacts:
  files:
     - **/*.war   
     - run4MS.sh
     - appspec.yml
     - scripts/*
     - src/*
  discard-paths: yes
