version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Building the seamfix-geostore project on 'date'
      - ./gradlew bootJar
  post_build:
    commands:
     - echo Buld completed for seamfix-geostore project on 'date'
artifacts:
  files:
     - build/libs/*.jar   
     - run4MS.sh
     - appspec.yml
     - scripts/*
  discard-paths: yes
