version: 0.2

phases:
  install:
    commands:
      - echo Installing maven 
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo Building the seamfix-geostore project on 'date'
      - mvn clean install
  post_build:
    commands:
     - echo Buld completed for seamfix-geostore project on 'date'
     - mvn package
artifacts:
  files:
    - $CODEBUILD_SRC_DIR/**/*.war
    - $CODEBUILD_SRC_DIR/**/doc/sql/001_setup_db.sql
    - $CODEBUILD_SRC_DIR/**/doc/sql/002_create_schema_postgres.sql
    - $CODEBUILD_SRC_DIR/**/doc/sql/002_create_schema_postgres.sql
    - arn:aws:s3:::seamfix-geostore/appspec.yml
    - arn:aws:s3:::seamfix-geostore/scripts/*
  discard-paths: yes
